# Generated by Django 5.0.6 on 2024-06-02 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('сonstructionСompany', '0003_remove_warehouse_price_remove_warehouse_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='purchase',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
    ]
